### ISSUE TITLE
Missing Gift Endpoint

### ISSUE THREAD

**Issue by Vaillantt** [BlossomiShymae/Needlework#2]
Hey, your project is really great and intuitive, but I noticed that the endpoint to send gifts or to receive information about received gifts is missing.

**Comment by BlossomiShymae** [comment]
Such endpoints are intentionally not supported to prevent a cease & desist, therefore, I cannot offer help for anything relating to shop, gifting, chat, authentication, Riot client, automation, name reveal, etc. This tool provides generated endpoints [as-is](https://raw.githubusercontent.com/dysolix/hasagi-types/main/swagger.json). Hope you understand. :>
